### ISSUE TITLE
First Scan is not NULL Probe

### ISSUE THREAD

**Issue by Fenguopeng** [nixawk/nmap_vscan#1]
I think the first scan probe is NULL,because NULL probe no 'ports'.eg i scan 3306,it will be first scan in_probes

**Comment by nixawk** [comment]
@Fenguopeng Please paste issue details here. I am getting confused. 

```
$ uname -a
$ python -V
```

```
$ python
>>> from nmap_vscan import vscan
>>> nmap = vscan.ServiceScan('./nmap-service-probes')
>>> .... what you have done ?
```
